# render.yaml
services:
  - type: web
    name: tushinde-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tushinde-db
          property: connectionString
      - key: ADMIN_API_KEY
        value: secret-tushinde-key
      - key: BONGA_API_CLIENT_ID
        value: 123456
      - key: BONGA_API_KEY
        value: yFU5LWq38JcyU+/ioD6fWIfhDSKDRvHOw/hhIngM968=
      - key: BONGA_API_SECRET
        value: lNsISnTGGguKfgGtwE2c5zvJv2e1OoSP
      - key: BONGA_SERVICE_ID
        value: 1

databases:
  - name: tushinde-db
    databaseName: tushinde
    user: tushinde_user
